version: "3.1"
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    image: sandboxapp
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www
  
  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginix
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: mysql:8.0 
    container_name: db
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: r00tadmin
    ports:
      - '3308:3306'
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local